### ISSUE TITLE
Project list view: Cards get too narrow

### ISSUE THREAD

**Issue by shibatas** [chingu-voyage3/bears-20#16]
As number of projects larger, the cards are becoming too narrow. We should:

* Wrap the cards (ex. using flexbox) and set min-width to each card. 
* Limit the number of cards in view... maybe we need a separate "full list" page, and show only a handful of cards on the landing page.

**Comment by AlexGherardelli** [comment]
I've fixed this in the current branch I'm working on - Bootstrap 4 uses flexbox, so it was just a matter of changing classes. I agree that we should have only few on the landing page and a full project page with all of them (possibly with filtering/search capabilities in the future). I'd be happy to work on having the landing page looking more "landing" :)
