### ISSUE TITLE
Project Detail goes blank

### ISSUE THREAD

**Issue by shibatas** [chingu-voyage3/bears-20#7]
Project details page goes blank if I refresh the page.

**Comment by marckimbrey** [comment]
Fixed by converting  Project Detail component to a function as its just handling props that are passed to it. If we wanted to keep it as a class we would need to initialise state in the constructor and use componentWillRecieveProps()  to set the state on props change.

**Comment by shibatas** [comment]
Great! I confirmed that the issue is gone now. As we work on other components, I'll keep in mind to use one of the methods you mentioned.
